---
- name: Copy cron scripts
  copy:
    src: "{{ item }}"
    dest: /root/cron_scripts/
    mode: 500
  with_fileglob:
    - ../files/*
  tags: cron

- name: Creates cron logs directory
  file: path=/root/cron_logs state=directory

- name: Cron job | Sync app files
  cron:
    name: Sync app files
    minute: 0
    job: /root/cron_scripts/app_files_sync.sh
  tags: cron

- name: Cron job | Sync WAL logs
  cron:
    name: Sync WAL logs
    minute: '*/10'
    job: /root/cron_scripts/wal_sync_to_aws.sh
  tags: cron

- name: Cron job | PG Base Backup
  cron:
    name: Backup and upload pg base
    minute: 0
    hour: 5
    job: /root/cron_scripts/pg_base.sh
  tags: cron
