---
# Place to get apt repository key
apt_key_url: "hkp://ha.pool.sks-keyservers.net"
# apt repository key signature
apt_key_sig: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
# apt keyring file
keyring: "/etc/apt/trusted.gpg.d/docker.gpg"
# Name of the apt repository for Docker CE or EE
apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"

# Version and edition
docker_edition: ce
docker_version: 17.12.0
docker_distribution: '{{ ansible_local.core.distribution
                         if (ansible_local|d() and ansible_local.core|d() and
                             ansible_local.core.distribution|d())
                         else ansible_distribution }}'

docker_users: [root]
